name: backend-notes
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.2.25=haa95532_0
  - expat=2.7.1=h8ddb27b_0
  - libffi=3.4.4=hd77b12b_1
  - openssl=3.0.16=h3f729d1_0
  - pip=25.1=pyhc872135_2
  - python=3.10.18=h981015d_0
  - setuptools=78.1.1=py310haa95532_0
  - sqlite=3.45.3=h2bbff1b_0
  - tk=8.6.14=h5e9d12e_1
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py310haa95532_0
  - xz=5.6.4=h4754444_1
  - zlib=1.2.13=h8cc25b3_1
  - pip:
      - annotated-types==0.7.0
      - anyio==4.9.0
      - attrs==25.3.0
      - backoff==2.2.1
      - bcrypt==4.3.0
      - build==1.2.2.post1
      - cachetools==5.5.2
      - certifi==2025.7.9
      - charset-normalizer==3.4.2
      - chromadb==1.0.15
      - click==8.2.1
      - colorama==0.4.6
      - coloredlogs==15.0.1
      - distro==1.9.0
      - durationpy==0.10
      - exceptiongroup==1.3.0
      - fastapi==0.109.0
      - filelock==3.18.0
      - flatbuffers==25.2.10
      - fsspec==2025.5.1
      - google-auth==2.40.3
      - googleapis-common-protos==1.70.0
      - grpcio==1.73.1
      - h11==0.16.0
      - httpcore==1.0.9
      - httptools==0.6.4
      - httpx==0.28.1
      - huggingface-hub==0.33.4
      - humanfriendly==10.0
      - idna==3.10
      - importlib-metadata==8.7.0
      - importlib-resources==6.5.2
      - jinja2==3.1.6
      - jiter==0.10.0
      - joblib==1.5.1
      - jsonschema==4.24.0
      - jsonschema-specifications==2025.4.1
      - kubernetes==33.1.0
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - mdurl==0.1.2
      - mmh3==5.1.0
      - mpmath==1.3.0
      - networkx==3.4.2
      - numpy==2.2.6
      - oauthlib==3.3.1
      - onnxruntime==1.22.1
      - openai==1.95.1
      - opentelemetry-api==1.35.0
      - opentelemetry-exporter-otlp-proto-common==1.35.0
      - opentelemetry-exporter-otlp-proto-grpc==1.35.0
      - opentelemetry-proto==1.35.0
      - opentelemetry-sdk==1.35.0
      - opentelemetry-semantic-conventions==0.56b0
      - orjson==3.10.18
      - overrides==7.7.0
      - packaging==25.0
      - pillow==11.3.0
      - posthog==5.4.0
      - protobuf==6.31.1
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pybase64==1.4.1
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pygments==2.19.2
      - pypika==0.48.9
      - pyproject-hooks==1.2.0
      - pyreadline3==3.5.4
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.1.1
      - python-multipart==0.0.7
      - pyyaml==6.0.2
      - referencing==0.36.2
      - regex==2024.11.6
      - requests==2.32.4
      - requests-oauthlib==2.0.0
      - rich==14.0.0
      - rpds-py==0.26.0
      - rsa==4.9.1
      - safetensors==0.5.3
      - scikit-learn==1.7.0
      - scipy==1.15.3
      - sentence-transformers==5.0.0
      - shellingham==1.5.4
      - six==1.17.0
      - sniffio==1.3.1
      - starlette==0.35.1
      - sympy==1.14.0
      - tenacity==9.1.2
      - threadpoolctl==3.6.0
      - tokenizers==0.21.2
      - tomli==2.2.1
      - torch==2.7.1
      - tqdm==4.67.1
      - transformers==4.53.2
      - typer==0.16.0
      - typing-extensions==4.14.1
      - typing-inspection==0.4.1
      - urllib3==2.5.0
      - uvicorn==0.35.0
      - watchfiles==1.1.0
      - websocket-client==1.8.0
      - websockets==15.0.1
      - zipp==3.23.0
prefix: C:\Users\vdgar\.conda\envs\backend-notes
